build_from:
  aarch64: library/alpine:3.23.2
  amd64: library/alpine:3.23.2
labels:
  org.opencontainers.image.description: Chromium runner in headless mode for browser
    automation
  org.opencontainers.image.licenses: Apache License 2.0
  org.opencontainers.image.source: https://github.com/miaucl/ha-addons
  org.opencontainers.image.title: 'Home Assistant Add-on: Chromium Runner'
