# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Chrome Runner
version: "2.0.0a0"
slug: chrome_runner
description: Chrome runner in headless mode for browser automation
panel_icon: "mdi:google-chrome"
panel_admin: false
codenotary: cyrill.raccaud+ha@gmail.com
url: "https://github.com/miaucl/ha-addons/tree/main/chrome-runner"
arch:
  - aarch64
  - amd64
init: false
ports:
  9223/tcp: 9222
map:
  - share:rw
tmpfs: true
image: "ghcr.io/miaucl/{arch}-chrome-runner"
