# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: jlesage/baseimage-gui:alpine-3.20-v4
  amd64: jlesage/baseimage-gui:alpine-3.20-v4
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Chrome"
  org.opencontainers.image.description: "Chrome GUI allowing for browser automation."
  org.opencontainers.image.source: "https://github.com/miaucl/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  signer: cyrill.raccaud+ha@gmail.com
  base_image: notary@home-assistant.io