build_from:
  aarch64: jlesage/baseimage-gui:alpine-3.20-v4.6.3
  amd64: jlesage/baseimage-gui:alpine-3.20-v4.6.3
codenotary:
  base_image: notary@home-assistant.io
  signer: cyrill.raccaud+ha@gmail.com
labels:
  org.opencontainers.image.description: Chrome GUI allowing for browser automation.
  org.opencontainers.image.licenses: Apache License 2.0
  org.opencontainers.image.source: https://github.com/miaucl/ha-addons
  org.opencontainers.image.title: 'Home Assistant Add-on: Chrome'
