apparmor: false
arch:
- aarch64
- amd64
codenotary: cyrill.raccaud+ha@gmail.com
description: Chrome GUI for testing and extended browser automation
environment:
  KEEP_APP_RUNNING: '1'
  USER_ID: '0'
image: ghcr.io/miaucl/{arch}-chrome
ingress: true
ingress_port: 5800
init: false
map:
- share:rw
name: Chrome
panel_admin: false
panel_icon: mdi:google-chrome
ports:
  5800/tcp: null
  5900/tcp: null
  9223/tcp: 9222
slug: chrome
url: https://github.com/miaucl/ha-addons/tree/main/chrome
version: 1.1.0
