# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Chrome
version: "1.0.0a0"
slug: chrome
description: Chrome GUI allowing for browser automation.
panel_icon: "mdi:google-chrome"
panel_admin: false
codenotary: cyrill.raccaud+ha@gmail.com
url: "https://github.com/miaucl/ha-addons/tree/main/chrome"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 5800
ports:
  9223/tcp: 9222
map:
  - share:rw
  - type: data
    path: /config
tmpfs: true
image: "ghcr.io/miaucl/{arch}-chrome"
