# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Chrome
version: "1.0.0a7"
slug: chrome
description: Chrome GUI allowing for browser automation.
panel_icon: "mdi:google-chrome"
panel_admin: false
codenotary: cyrill.raccaud+ha@gmail.com
url: "https://github.com/miaucl/ha-addons/tree/main/chrome"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
ingress: true
ingress_port: 5800
ports:
  5800/tcp: null
  5900/tcp: null
  9223/tcp: 9222
environment:
  # Required to write to /data
  USER_ID: "0"
  KEEP_APP_RUNNING: "1"
map:
  - share:rw
image: "ghcr.io/miaucl/{arch}-chrome"
legacy: true
options:
  VNC_PASSWORD: ""
  SECURE_CONNECTION: "0"
  SECURE_CONNECTION_VNC_METHOD: "SSL"
  SECURE_CONNECTION_CERTS_CHECK_INTERVAL: "60"
schema:
  SECURE_CONNECTION: str
  SECURE_CONNECTION_VNC_METHOD: str
  SECURE_CONNECTION_CERTS_CHECK_INTERVAL: str