# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: noVNC"
  org.opencontainers.image.description: "GUI of bare debian via noVNC."
  org.opencontainers.image.source: "https://github.com/miaucl/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary: no
codenotary.signer: cyrill.raccaud+ha@gmail.com
codenotary.base_image: notary@home-assistant.io