# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: noVNC"
  org.opencontainers.image.description: "GUI of bare debian via noVNC."
  org.opencontainers.image.source: "https://github.com/miaucl/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  signer: cyrill.raccaud+ha@gmail.com
  base_image: notary@home-assistant.io