# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: noVNC
version: "1.0.0a16"
slug: novnc
description: GUI of bare debian via noVNC
panel_icon: "mdi:remote-desktop"
apparmor: false
panel_admin: false
codenotary: cyrill.raccaud+ha@gmail.com
url: "https://github.com/miaucl/ha-addons/tree/main/novnc"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_entry: ingress.html
ports:
  5900/tcp: null
  5901/tcp: 5901 # temp
  13011/tcp: 13011
map:
  - share:rw
tmpfs: true
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/miaucl/{arch}-novnc"
