# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: noVNC
version: "1.0.0a0"
slug: novnc
description: GUI of bare debian via noVNC
panel_icon: "mdi:linux"
apparmor: false
panel_admin: false
url: "https://github.com/miaucl/ha-addons/tree/main/novnc"
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
init: false
ingress: true
ingress_port: 8080
ports:
  8080/tcp: null
  13011/tcp: 13011
map:
  - share:rw
tmpfs: true
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/miaucl/{arch}-novnc"
