# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: noVNC
version: "1.0.0a2"
slug: novnc
description: GUI of bare debian via noVNC
panel_icon: "mdi:remote-desktop"
apparmor: false
panel_admin: false
url: "https://github.com/miaucl/ha-addons/tree/main/novnc"
arch:
  - aarch64
  - amd64
init: false
ingress: true # novnc/vnc_lite.html?scale=yes
ingress_port: 8080
ingress_entry: novnc/vnc.html?resize=remote&path=novnc/websockify
ports:
  8080/tcp: 8080
  13011/tcp: 13011
map:
  - share:rw
tmpfs: true
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/miaucl/{arch}-novnc"
