build_from:
  aarch64: jlesage/baseimage-gui:alpine-3.20-v4.9.0
  amd64: jlesage/baseimage-gui:alpine-3.20-v4.9.0
labels:
  org.opencontainers.image.description: Chromium GUI for testing and extended browser
    automation
  org.opencontainers.image.licenses: Apache License 2.0
  org.opencontainers.image.source: https://github.com/miaucl/ha-addons
  org.opencontainers.image.title: 'Home Assistant Add-on: Chromium'
