# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/linuxserver/baseimage-kasmvnc:arm64v8-debianbookworm"
  amd64: "ghcr.io/linuxserver/baseimage-kasmvnc:amd64-debianbookworm"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Chromium"
  org.opencontainers.image.description: "Add a Chromium browser to your web ui."
  org.opencontainers.image.source: "https://github.com/miaucl/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
